version: '3.8'

services:
  api:
    build: .
    container_name: flight-management-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/venv  # Exclure venv du volume
    environment:
      - DATABASE_URL=sqlite:///./app.db
    restart: unless-stopped
    command: sh -c "python init_db.py && python seed_data.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
